### PR TITLE
Solved issue 319

### LINKED ISSUE #319: Add Reminder in the Welcome Bot to Star the Meshery.io Project
**Current Behavior**
 A welcome bot has been configured to usher in contributors new to this project. However, a reminder to star the project is missing in the message.

**Desired Behavior**
 The [config.yml](https://github.com/layer5io/meshery.io/blob/master/.github/config.yml) should be updated, you can take a cue from the highlighted [line 22](https://github.com/layer5io/meshery-consul/blob/master/.github/config.yml#L22)

### PR DESCRIPTION
**Pull request by hikky08**
Signed-off-by: hikky08 <ikrambabs@gmail.com>

**Description**

This PR fixes #319

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Please `[star](<link>)` the proj.....If you have not yet done it!

**Review by PluckyPrecious — APPROVED** [review]
You did it!🥳

**Comment by PluckyPrecious** [comment]
:star: Please [star the project](../stargazers) if you have yet to do so.

> Please `[star](<link>)` the proj.....If you have not yet done it!

Hi @Nikhil-Ladha any reason why you’d prefer it this way? It might be slightly off from other repo.🤔

**Comment by Nikhil-Ladha** [comment]
Well the English seemed a bit off to me. If it's same in other repos, then one thing that must be changed is have-> are

**Comment by Ruth-ikegah** [comment]
Yeah true, are is a better word!

**Comment by PluckyPrecious** [comment]
Yep! Fell same way too, I think he copied as seen in the referenced repo. Not a bad idea to make the correction. 👌🏽

**Comment by hikky08** [comment]
oh thank you so much Lee, i had a Problem with my laptop that is why i
havent edited the code since

**Comment by leecalcote** [comment]
@hikky08 no sweat. It'd been some time that I'd been able to review a few PRs. I didn't want to be the bottleneck here. Thanks for taking on this and other issues. 😄

**Pull request merged**
