### PR TITLE
Added Program Section

### LINKED ISSUE #297: [Child] Add CNCF Landscape logo to meshery.io
**Current Behavior**
Meshery has been accepted into the CNCF Landscape - https://layer5.io/news/meshery-accepted-into-cncf-landscape

**Desired Behavior**
This fact should be reflected on the meshery.io website alongside other programs that Meshery is participating in (e.g. GSoC, CommunityBridge and so on).

**Implementation**
- Select one of the SVGs here - https://github.com/cncf/artwork/tree/master/other/cncf-landscape - based on the most appropriate fit in context of other logos in the Participation section of the site.

### LINKED ISSUE #298: [Parent] Add Program Participation section on meshery.io
**Current Behavior**
Meshery participation in a number of programs. 

**Desired Behavior**
A new section should be created to display the logos of these programs (e.g. GSoC, CommunityBridge and so on).

**Implementation**
- See related issues: #297

### PR DESCRIPTION
**Pull request by koladeafeez**
- modify community link

Signed-off-by: kolade Afeez <daisedalok@gmail.com>

**Description**

(PARENT) This PR fixes #298 
(CHILD) This PR fixes #297 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Whoa! No small piece of work completed here, @koladeafeez. Thank you for taking this on. 

There are a number of points of feedback to give here. I anticipate the reviewers being meticulous in their review. Be thankful if they are (it's through such feedback that an engineer grows) and be cognizant that scrutiny comes from a place of pride and love for the projects in the community.

A list of logos would have minimally sufficed. What you've accomplished here is more than I was expecting. Good stuff. 👍

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Good work here @koladeafeez , but still a lot of changes are needed..
1. The programs page should not open in a different tab.
2. Any specific reason, to not use the md files, directly and follow the page format?(Means, it will reduce be easier and consistent with other sites and data here)

Now, I am attaching screenshots and will explain wrt that.
Screenshot from 2020-09-10 19-40-36
Here, the navbar color and the body color is inverted, from the original site. Gradient effect on the cards doesn't looks good TBH. It would be better if you could add a hover effect on the cards like color change and box-shadow.

Screenshot from 2020-09-10 19-40-19
The vertical divider on the leftmost side is not needed.
The whitespace in the right side looks a bit odd and empty, for that either the orientation may be changed to row wise instead of column or the column width can be increased. 
On hovering the `Participate` button the cursor should change to `pointer`.

Screenshot from 2020-09-10 19-40-26
Here, in the image of Meshery in CNCF Landscape, is a bit ambiguous considering the scrollbar and the top-right `X` button, which makes it look like some element to interact with.
The line `Meshery now featured in the CNCF Landscape` can be made more prominent.
Also, the row-wise design here looks better and complete, the same can be followed for other programs as well, or all of them should follow the same rule (row/column).

- The button hover effect and design rule applies for all the programs.
- The footer seems to have reduced padding in the programs page, do take a look into that too.
- Last but not the least, the most important part the programs page has many responsive issues, Please fix that.

Hopefully, I was clear in all my points. If you face any issues anywhere or want to discuss design aspects, you can ping me on slack.

**Comment by koladeafeez** [comment]
Thank you @Nikhil-Ladha for the feedback, I will make the changes

**Comment by Nikhil-Ladha** [comment]
Good improvement over here @koladeafeez . Just a few more things to rectify:
- The background should be the same as the main page like this 
Screenshot from 2020-09-12 16-26-42
- The hover effect of the card needs some changes, the color change, and transform-scale should not happen instead, the effect that we have on the layer5.io site is nice to keep it here too. Like this:
Screenshot from 2020-09-12 16-26-45
I don't know if the effect is visible to you or not in the first card of the image, just a light black shadow with a minimal transition. Using a similar property from layer site `transition: box-shadow .25s, -webkit-box-shadow .25s`.
- Also, please move the inline CSS to the external CSS file.

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Good work. But few issues occurred after the last change:
- The Google Season of Docs page has broken.
- The color change on clicking the card can be removed.
Screenshot from 2020-09-13 13-41-59
- The link for issues at the bottom is going out of the text area
Screenshot from 2020-09-13 13-42-34
- Increase some margin at the bottom for this page
Screenshot from 2020-09-13 13-42-49
- Please move the inline CSS in the subscribe.html and the programs.html page to an external CSS file.
- Also, the console.log line in the main.js file, at line 8 can be removed

**Review by Nikhil-Ladha — APPROVED** [review]
Thanks for the updates @koladeafeez , and bearing with my long reviews :') It looks great now.
Good work:+1:

**Comment by koladeafeez** [comment]
You gave a fantastic review. Thank you, I also like how it look now

**Comment by Nikhil-Ladha** [comment]
> You gave a fantastic review. Thank you, I also like how it look now

It's all your hard work visible up there on the site :tada:

**Review by Neilblaze — COMMENTED** [review]
This is a huge update to the page! 
Thank you @koladeafeez :smiley: :tada: 

& also special shoutout to @Nikhil-Ladha for the consistant review :smile:

**Comment by koladeafeez** [comment]
Thanks @Neilblaze

**Pull request merged**
