### PR TITLE
correction in preference of fonts

### PR DESCRIPTION
**Pull request by vineethvanga18**
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>

### CODE REVIEW

**Comment by leecalcote** [comment]
> Deploy preview for _mesheryio_ ready!
> 
> Built with commit [4eee09e](https://github.com/layer5io/meshery.io/commit/4eee09ef5f40ffc904eb09272c2de49798dbfd82)
> 
> https://deploy-preview-244--mesheryio.netlify.app

@vineethvanga18 Open Sans isn't showing in the deployment for me. Is it for you?

**Comment by vineethvanga18** [comment]
@leecalcote I tested it on chrome, fire fox, IE ,safari(lambda online test) It is working on them.

chrome:
chrome_test

IE:
IE_test

safari:
safari_test

**Comment by leecalcote** [comment]
These look great, @vineethvanga18! Are these screenshots of those browsers when pointed at the netlify deployment preview?

**Comment by leecalcote** [comment]
Wait a minute... I now see Open Sans in Safari on the netlify deployment preview, too. Weird.

**Pull request merged**
