### PR TITLE
Add Dynamic SMI Table

### PR DESCRIPTION
**Pull request by utkarsh-pro**
**Description**

This PR adds dynamic SMI Table support on `https://meshery.io/smi`. Jekyll doesn't supports dynamic content out of the box so a new plugin which adds a new fluid tag to jekyll is also added here.

Usage of the newly created tag: `{% externalJSON data from url <api-endpoint-here> %}`

Relevant Screenshot:
Screenshot_20210401_175323

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
With smi-spec.io running on Hugo, I suppose this means that we'll need an alternative implementation.

Using the `externalJSON` plugin, the table data is refreshed on page load, correct?y

**Comment by utkarsh-pro** [comment]
> With smi-spec.io running on Hugo, I suppose this means that we'll need an alternative implementation.
> 
> Using the `externalJSON` plugin, the table data is refreshed on page load, correct?

Yes, using the plugin the data is fetched before rendering the page on the server side and then fed to jekyll (hence jekyll consider it another static json).

I am not sure if I understood the alternative implementation part :sweat_smile:

**Review by dhruv0000 — APPROVED** [review]

**Comment by leecalcote** [comment]
@dhruv0000 we're missing the version of the SMI Conformance test (the Learn Layer5 release) in this table. Is that version available in the results endpoint?

**Comment by leecalcote** [comment]
@utkarsh-pro whee! The "alternative implementation" bit is in reference to the next step in this effort being the publishing this same table of results on https://smi-spec.io, which runs on Hugo.

**Comment by dhruv0000** [comment]
> @dhruv0000 we're missing the version of the SMI Conformance test (the Learn Layer5 release) in this table. Is that version available in the results endpoint?

Yes it is. Let me fix this.

**Pull request merged**
