### PR TITLE
readme updated

### PR DESCRIPTION
**Pull request by soham4abc**
**Description**

Updated the Readme at par with the Meshery Project

**Notes for Reviewers**
Pls have a look at the readme 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by soham4abc** [comment]
> Thank you for picking this issue.
> please remove the link in the "community drive", we don't need it anymore.

Done as per request. Pls have a look.

**Review by Anita-ihuman — APPROVED** [review]

**Comment by Anita-ihuman** [comment]
Great work @soham4abc, Thank you for taking this up.

**Comment by soham4abc** [comment]
> Great work @soham4abc, Thank you for taking this up.

Thank you 
@leecalcote  Please review!

**Review by leecalcote — APPROVED** [review]
Looks good to me. 👍

**Pull request merged**
