### PR TITLE
add layer5 as creator of meshery to footer

### LINKED ISSUE #417: [Footer] Adding Layer5 as the creator of meshery to the footer
**Current State:**
We current have only navlinks highlighting just Layer5 as the creator of meshery

**Desired State:**
Adding Layer5 as the creator of Meshery to the footer of  Meshery

Below is the desired design and the design link

https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1165%3A1044

footer

Here is the link to the Layer5 logo
https://drive.google.com/file/d/1A3A-YNkM5Ak9tVcM1Ryu_c3paEQiIggw/view?usp=sharing

### PR DESCRIPTION
**Pull request by Thea10**
Signed-off-by: Cynthia <olucynakin@gmail.com>

**Description**

This PR fixes #417

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@austinogiza a preview of this change is available here - https://deploy-preview-432--mesheryio.netlify.app

**Comment by austinogiza** [comment]
> @austinogiza a preview of this change is available here - https://deploy-preview-432--mesheryio.netlify.app

This is nice 💥

**Comment by leecalcote** [comment]
@austinogiza did you produce a design for review?

**Comment by austinogiza** [comment]
> @austinogiza did you produce a design for review?

@leecalcote  yes I did

https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=1596%3A67

**Comment by Thea10** [comment]
@leecalcote @austinogiza   can I go ahead with that?

**Comment by leecalcote** [comment]
@Thea10, if you would, for now place the copyright line and the logo line side-by-side. I think what you have is a step forward.

**Review by leecalcote — APPROVED** [review]
Looking good, @Thea10! 😄

**Comment by leecalcote** [comment]
Yay, @Thea10! 🎈

**Pull request merged**
