### PR TITLE
Test

### PR DESCRIPTION
**Pull request by kushthedude**

### CODE REVIEW

**Comment by kushthedude** [comment]
@leecalcote Netlify is up for the meshery.io 🎉 . You can see the previews in PRs, also after every commit to master netlify will publish at https://mesheryio.netlify.com

**Comment by leecalcote** [comment]
Looking good, @kushthedude. 👍 Is there a configuration that can be made in Netlify to deploy a robots.txt with ```User-agent: * Disallow: /``` to the preview site?

**Comment by kushthedude** [comment]
> Looking good, @kushthedude. 👍 Is there a configuration that can be made in Netlify to deploy a robots.txt with `User-agent: * Disallow: /` to the preview site?

The site is deployed from the repo itself, so it will pick the robot.txt stored in the repository without the need of specifying it more explicitly .

**Comment by kushthedude** [comment]
I think its time to close the test PR now.

**Comment by leecalcote** [comment]
Regarding robots.txt, that behavior makes sense, which is why I consider it would be good to disallow indexing of the preview site (to avoid negatively impacting SEO). 

From the looks of this thread, it seems Netlify might be implicitly addressing this issue - https://community.netlify.com/t/avoid-seo-duplicated-content-between-master-url-and-actual-production-url/850/4

**Comment by leecalcote** [comment]
@kushthedude I checked the PR preview sites. Each page does carry the `x-robots-tag: noindex` header, however, the two site deployments mesheryio.netlify... and layer5io.netlify... don't carry this header and have a robots.txt that allows all web crawlers. I think there are a couple options to use to overcome this issue. Post processing capabilities in Netlify might be one.

**Comment by kushthedude** [comment]
What about using layer5.io as our domain rather than layer5io.netlify.com ? This will enable us to trigger the new builds and publish the site with help of netlify instead of relying on GitHub Pages .

**Pull request closed without merging**
