### PR TITLE
Added Ericsson logo to Used By section

### LINKED ISSUE #346: Add Ericsson's logo to the Used By section
**Current State of the Meshery.io site**
Ericsson is not listed as a user. See Meshery [ADOPTERS](https://github.com/layer5io/meshery/blob/master/ADOPTERS.md) file. 

**Desired State of the Meshery.io site**
Given use by employee's at Ericsson, add Ericsson's logo to those under the **Used By** section.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by blee1710**
Signed-off-by: blee1710 <s3707616@student.rmit.edu.au>

**Description**

This PR fixes #346

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by kishore007k** [comment]
@blee1710  Nice work here. 
Some small changes and we are good to go.
1. It would be nice if the Icons container fills the full width like this.
Capture27
2. If you could reduce the size of the Ericsson Icon. It seems a little bigger than the others.

**Comment by blee1710** [comment]
Thank you for your feedback, @kishore007k!

I've made some changes and pushed it for review.

**Comment by kishore007k** [comment]
> Thank you for your feedback, @kishore007k!
> 
> I've made some changes and pushed it for review.

The Ericsson logo seems a bit bigger than the rest of the logos could you reduce the size of that.

**Review by kishore007k — CHANGES_REQUESTED** [review]
Reduce the size of the Ericsson Logo to fit the size of the other logos.

**Comment by blee1710** [comment]
> 
> 
> Reduce the size of the Ericsson Logo to fit the size of the other logos.

Sorry about that, had a misunderstanding about the image size! I've made changes and I think it resolves the issue now.

**Review by kishore007k — APPROVED** [review]
Great work 🤘 @blee1710

**Review by JubayerJoy — COMMENTED** [review]
The Erricson logo has some padding builtin, unlike others. It is causing a padding-left in mobile view. Consider trimming the blank parts in the logo.

Really good work, everything else LGTM :+1:

screenshot-deploy-preview-347--mesheryio netlify app-2020 10 19-23_28_01

**Comment by blee1710** [comment]
Hi @JubayerJoy,

I had to edit the original logo to add the white space to prevent it from looking bigger than the other logos. I see the need to change it back, do you have any suggestions as to how to make it looks smaller when there is no white space though?

Thank you

**Comment by JubayerJoy** [comment]
> Hi @JubayerJoy,
> 
> I had to edit the original logo to add the white space to prevent it from looking bigger than the other logos. I see the need to change it back, do you have any suggestions as to how to make it looks smaller when there is no white space though?
> 
> edit: I'll try trimming it first!
> 
> Thank you

Hi @blee1710,
You should trim the white spaces and add some left-padding to the logo. Also by using `media query`, you can remove those left-padding to keep the alignment similar to top logos in mobile-view.

Good luck 🤞

**Comment by blee1710** [comment]
> > Hi @JubayerJoy,
> > I had to edit the original logo to add the white space to prevent it from looking bigger than the other logos. I see the need to change it back, do you have any suggestions as to how to make it looks smaller when there is no white space though?
> > edit: I'll try trimming it first!
> > Thank you
> 
> Hi @blee1710,
> You should trim the white spaces and add some left-padding to the logo. Also by using `media query`, you can remove those left-padding to keep the alignment similar to top logos in mobile-view.
> 
> Good luck 🤞

Hi @JubayerJoy, I've given it a shot!

Thanks again for your feedback and assistance.

**Comment by leecalcote** [comment]
Thanks for sticking with this, @blee1710. 👍

**Comment by JubayerJoy** [comment]
@blee1710, very nice work!
Though this PR looks good to go, the Ericson logo looks pixelated, consider using a clearer version of this logo.

screenshot-deploy-preview-347--mesheryio netlify app-2020 10 20-18_30_16

Thank you 🎈

**Review by JubayerJoy — COMMENTED** [review]
@blee1710, very nice work!
Though this PR looks good to go, the Ericson logo looks pixelated, consider using a clearer version of this logo.

screenshot-deploy-preview-347--mesheryio netlify app-2020 10 20-18_30_16

Thank you 🎈

**Comment by blee1710** [comment]
> 
> 
> @blee1710, very nice work!
> Though this PR looks good to go, the Ericson logo looks pixelated, consider using a clearer version of this logo.
> 
> screenshot-deploy-preview-347--mesheryio netlify app-2020 10 20-18_30_16
> 
> Thank you 🎈

Sorry about that! Was an issue with my image editor. Should be fixed in the upcoming commit! 

Thank you

**Comment by leecalcote** [comment]
It's a shame that the ```filter: grayscale(75%);``` doesn't seem to have an effect on the Ericsson logo.

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Looking good, @blee1710.

**Comment by blee1710** [comment]
> 
> 
> It's a shame that the `filter: grayscale(75%);` doesn't seem to have an effect on the Ericsson logo.

It's possible to make it work by using an alternative logo! I've tried it on my own and it looks like this:

pre-hover

post-hover

If the colour/different logo style look okay I can add that in!

**Comment by leecalcote** [comment]
Oooh, very nice! 😄

**Comment by blee1710** [comment]
> 
> 
> Oooh, very nice! 😄 Let's do it.

All done!

**Comment by leecalcote** [comment]
oh, no. Why didn't our newcomer welcome message get displayed here? 😞  Hmm. This needs fixed. In the meantime, here's this, @blee1710 - https://github.com/layer5io/layer5/pull/978#issuecomment-711783727

You're most welcome to join the Layer5 Community - http://slack.layer5.io. Warm and welcoming folks inside.

**Review by JubayerJoy — COMMENTED** [review]
Very very nice work! 👌

**Pull request merged**
