### PR TITLE
[Feature] - Updated Footer & Fixed File Name

### LINKED ISSUE #431: [Feature] - Add SMI Conformace to the Meshery Site Footer
**Current State of the Meshery.io site**
The footer of [meshery.io](https://meshery.io) site does not have any link to [meshery.io/smi](https://meshery.io/smi) and hence a new link should be added here to direct to the SMI Page

**Existing:**
image

**Desired State of the Meshery.io site**
A Link to SMI Conformance to be added,

**Desired:**
image

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by adithyaakrishna**
Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Description**

This PR fixes #431 

**Notes for Reviewers**
- The file name was `nitish-malhotra .md `, which has been changed to `nitish-malhotra.md` as it was giving no such file found during build or serve
- Added SMI option to the footer

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thanks, @adithyaakrishna

**Review by Thea10 — CHANGES_REQUESTED** [review]
@adithyaakrishna  "Nitish Malhotra" is now duplicated in the contributors section. 

Check the community dropdown in the navigation bar and click contributors.


nitish

**Comment by adithyaakrishna** [comment]
Ohh, this is a strange error 😶
The contributor collection has only one file but still, the site has two. Will look into this 💯
image

**Comment by adithyaakrishna** [comment]
Lmao, my bad. I Modified file was added, but the existing one was still left in staged changes 😅

**Review by leecalcote — APPROVED** [review]
Thank you, @adithyaakrishna

**Pull request merged**
