### PR TITLE
Mshery blue highlighted texts are replaced

### PR DESCRIPTION
**Pull request by gunjanmimo**
Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

### CODE REVIEW

**Comment by kushthedude** [comment]
Why is this needed now? It has been fixed already!

**Comment by gunjanmimo** [comment]
Actually I made this mistake when I was making this new getting started section, where I presented the Meshery word in blue colour, as we know blue represent any hyperlink. So I removed blue color

**Comment by leecalcote** [comment]
@gunjanmimo [this PR's preview](https://deploy-preview-146--mesheryio.netlify.com) looks good. The changed include in this PR are to clean up unused `<spans>` and unused CSS, right?

**Comment by leecalcote** [comment]
Near as I can tell, we're good to go here: a little cleanup and a vector image.

**Pull request merged**
