### PR TITLE
Added author details

### LINKED ISSUE #165: Empty author contents on SMI blog
**Current State:**

Empty author contents on SMI blog

**Desired State:**

Remove the weird empty block or add author details.

**Screenshot**

Screenshot 2020-04-25 at 11 46 42 PM

---
**Contributor Resources**
- [Blog to be changed](https://meshery.io/blog/a-standard-interface-for-service-meshes)

### PR DESCRIPTION
**Pull request by Akanksha1212**
fixes #165 
Signed-off-by: Akanksha1212 <akankshasingh121297@gmail.com>

### CODE REVIEW

**Comment by NupurThakur27** [comment]
@Akanksha1212 you have not Signed your PR, to do the same please refer to the DCO Action Details from the list of checks mentioned.

**Comment by leecalcote** [comment]
@Akanksha1212 thank you! Regarding sign-off on your git commits, here is a bit of an explanation and tips on how to make commit signing automatic from now on - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin. In order to sign your commits on this specific PR, you can follow these steps - https://github.com/layer5io/meshery.io/pull/223/checks?check_run_id=784926628

**Comment by leecalcote** [comment]
@Akanksha1212 ping me, if I can help.

**Comment by kushthedude** [comment]
Hey @Akanksha1212 Any update here ?

**Comment by Akanksha1212** [comment]
Closing this for now. Will make a new pr.

**Pull request closed without merging**
