### PR TITLE
added CI WG Meeting Event and its link

### PR DESCRIPTION
**Pull request by Vineet-Sharma29**
Signed-off-by: Vineet-Sharma29 <vineet.s17@iiits.in>

### CODE REVIEW

**Comment by Vineet-Sharma29** [comment]
Should I change the text from "Participate in WG CI working group" to some other text. I think some users can get confused with this text.

**Comment by ashiscs** [comment]
fixes #162

**Comment by Vineet-Sharma29** [comment]
@leecalcote ok. I will refactor

**Comment by leecalcote** [comment]
Thank you, @Vineet-Sharma29. The updates that you've been making are very helpful. 💯 

If you do figure this out here, there's another location that has the same need - https://meshery.layer5.io/docs/overview#community

**Pull request merged**
