### PR TITLE
Added MetaBob in Adopters

### LINKED ISSUE #396: [Adopters] Add MetaBob to the list of adopters
**Current State of the Meshery.io site**
MetaBob is a Meshery user, but not listed on the meshery.io site.

**Desired State of the Meshery.io site**
MetaBob should be listed in the USED BY section of the site.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by chinmaym07**
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

**Description**

This PR fixes #396 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@chinmaym07, my apologies. I meant to list MetaBob, not OpenGov. Will you kindly update this PR to reflect https://metabob.com as the user instead?

**Review by sakomws — APPROVED** [review]
LGTM, thx so much!

**Review by sakows — APPROVED** [review]
lg, from 2nd git account seemed :) @leecalcote pls moving forward sakomws, i know its confusing :)

**Comment by leecalcote** [comment]
Aha! Very good. Will do.

**Review by sakomws — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]
Thank you, gents. Looks great. 👍

**Pull request merged**
