### PR TITLE
fixes #274

### LINKED ISSUE #274: [Community] Some of the community member profile pictures need to be squared (in aspect ratio)
**Description**
A number of the community member profile pictures are skewed by the constraints put on the picture as displayed with a circle affect on https://meshery.io/community.

**Expected Behavior**
The aspect ratio of each of the community member photos should be square, so as to avoid being skewed in shape.

**Implementation**
- In some cases, pictures can be cropped / adjusted to be square in shape.
- In other cases, a new picture may need to be requested from the member.

### PR DESCRIPTION
**Pull request by vineethvanga18**
Signed-off-by: vineethvanga18 <reddy.8@iitj.ac.in>

**Description**

This PR fixes #274 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by vineethvanga18** [comment]
Here's how it looks
Screenshot from 2020-07-24 13-18-59

**Comment by leecalcote** [comment]
@vineethvanga18 wioo you have a look at the first three of so profiles and Tanuj's? They seem to still be skewed.

**Comment by vineethvanga18** [comment]
@leecalcote on the community page or individual?

**Comment by leecalcote** [comment]
@vineethvanga18 oh, nice. I didn't look at your code change, yet. Yes, the individual pages look nice.

**Comment by vineethvanga18** [comment]
@leecalcote should I do the same to /community/ page,here the images are skewed,with "object-fit : cover" they wont be skewed and also we should request people whose image didn't fit well another image.

**Comment by leecalcote** [comment]
@vineethvanga18, yes, please do update the /community page in the same way.

**Pull request merged**
