### PR TITLE
Fixed transparent navbar issue

### LINKED ISSUE #325: NavBar of site needs improvement.
**Description**

Nav Bar doesn't behave properly on all pages and becomes transparent.

**Expected Behavior**

Just take a look at navbar colour in all pages.

**Screenshots**

image

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

### LINKED ISSUE #326: Fix the navbar visibility in Community & Blog pages
**Description**

The navigation bar of [Community](https://meshery.io/community/) & [Blog](https://meshery.io/blog/) pages of [Meshery](https://meshery.io/) page has gone completely blended with the background. As a result, nothing is visible on the navbar after the landing of the respective pages, but it becomes visible on scroll. This issue pertains for both desktop-view & mobile-view.

**Expected Behavior**

Make the navbar visible. Follow the screenshots provided below.

**Screenshots**

Currently the [Community](https://meshery.io/community/) looks like this :~
E1

It should be looking like this :~
S1

& for the [Blog](https://meshery.io/blog/) page, it's :~
E2

It should look like this :~
S2

Notice the navbar in both of the above references.

**Environment:**
 - Browser: [e.g. Chrome, Firefox, Opera]
 - Device: [e.g. laptop, Android 10]

---
[Optional] **To Reproduce**
1. Go to [Community](https://meshery.io/community/) & [Blog](https://meshery.io/blog/) pages
2. Inspect the navbar
3. Scroll down a bit.
4. See the visible navbar.

### PR DESCRIPTION
**Pull request by Nikhil-Ladha**
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

**Description**

This PR fixes #326 , fixes #325 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
It works in my tests on a mobile phone.

**Comment by Nikhil-Ladha** [comment]
> It works in my tests on a mobile phone.

The fix or the current site?

**Review by Neilblaze — APPROVED** [review]
Perfect! :ok_hand:

**Comment by leecalcote** [comment]
> > It works in my tests on a mobile phone.
> 
> The fix or the current site?

Sorry, I meant to say the Fixx Works. Whereas the current site menu does not work well on mobile

**Pull request merged**
