### PR TITLE
Added the community calendar and fixed issue #322

### PR DESCRIPTION
**Pull request by prasanjit15**
Hii, 
I have fixed issue#[322](https://github.com/layer5io/meshery.io/issues/322) by adding the community calendar and making the necessary changes. Kindly verify and merge it.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@prasanjit15 the DCO issue needs to be fixed and I think by mistake you have removed the twitter icon and link. Please check that.

**Comment by prasanjit15** [comment]
> @prasanjit15 the DCO issue needs to be fixed and I think by mistake you have removed the twitter icon and link. Please check that.
> 
> Okay, so from the code I get the issue. You need to add a hyphen i.e, `-` before the `name` label like others.

sorry my bad I missed it. I will just fix and do a PR.

**Comment by Nikhil-Ladha** [comment]
Hey, why did you close this PR?

**Comment by Nikhil-Ladha** [comment]
The changes looked good.

**Comment by prasanjit15** [comment]
Sorry I was not clear if this will add to changes so I created a new one. So, should I reopen This or you will merge the new one?

**Comment by Nikhil-Ladha** [comment]
You can reopen this one or create a new one whichever you feel you are comfortable with. Also, I think the link for the calendar is not correct can you please double check it.

**Comment by prasanjit15** [comment]
> You can reopen this one or create a new one whichever you feel you are comfortable with. Also, I think the link for the calendar is not correct can you please double check it.

@Nikhil-Ladha sorry But I asked the link that day because I was getting some kind of error. I am giving the exact same link as given in layer5.io i.e.,

"https://calendar.google.com/calendar/u/1/r?cid=bGF5ZXI1LmlvX2VoMmFhOWRwZjFnNDBlbHZvYzc2MmpucGhzQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20"

**Comment by Nikhil-Ladha** [comment]
This link is fine, maybe sime issue in the code. Do confirm things once from your end too.

**Comment by prasanjit15** [comment]
Please confirm that if I corrected and create a PR again I am not getting any option to merge then does it get merged automatically?

**Comment by prasanjit15** [comment]
By the way the problem was not in the code but in the link....here is the correct link 

https://bit.ly/2SbrRhe

**Comment by prasanjit15** [comment]
Now Please check if it is working

**Comment by prasanjit15** [comment]
> Please confirm that if I corrected and create a PR again I am not getting any option to merge then does it get merged automatically?

Lol, I figured it out :)

**Pull request closed without merging**
