### PR TITLE
update community section #245

### LINKED ISSUE #245: Community section needs updated to reflect many weekly meetings
**Current Behavior**
There are many different meetings held each week. The current community section doesn't list them all. 

**Desired Behavior**
Instead of saying “Join weekly community meeting on Fridays from 10am - 11am Central.“, it should say “Join community meetings on the community calendar.”

---
[Optional] **Alternatives**
Add the community calendar as described here - https://github.com/layer5io/meshery.io/issues/164

### PR DESCRIPTION
**Pull request by morrme**
Fixes #245
Signed-off-by: morrme <morrme@users.noreply.github.com>

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @morrme. A small item to attend to: signing your commits. Here are instructions to sign off on the commit inside this PR - https://github.com/layer5io/meshery.io/pull/248/checks?check_run_id=832698300

Here is instructions on configuring your dev environment automatically sign-off on your commits - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Comment by morrme** [comment]
@leecalcote Thanks. I did the edits in the browser, not locally, since it was just a few lines of text change. I tried to follow the model of other PRs but may not have done it correctly. Sorry about that!

**Comment by leecalcote** [comment]
No, that's fine. You're right - GitHub doesn't support signing commits through the web UI. Let me revive your PR and assist with the sign-off....

**Comment by leecalcote** [comment]
Congrats on your first PR merged in this project, @morrme. 🎈

**Pull request merged**
