### PR TITLE
Added other mailing list to [includes/subscribe]

### LINKED ISSUE #416: Mailing lists update
**Current State of the Meshery.io site**
Meshery has a couple of mailing lists:

https://groups.google.com/a/meshery.dev/g/community
https://groups.google.com/a/meshery.dev/g/dev
https://groups.google.com/a/meshery.dev/g/user

**Desired State of the Meshery.io site**
The https://meshery.io/subscribe page should have a link and short description of each.

The form on the page now is for the layer5.io mailer. It needs to stay, but these other three can be added. They won’t be forms, just links to groups.google.com

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by Lezette**
Signed-off-by: Elizabeth Lola <leezeelola@gmail.com>

**Description**

This PR fixes #416 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — COMMENTED** [review]
Looks good, just two items to fix:
- Please mention the issue number this PR references to in the description something like `This PR fixes #<issue-number>` this will automatically close the issue once the PR is merged.
- The blank space at the top of the head `Mailing Lists` can be reduced a bit.

**Comment by Lezette** [comment]
> Looks good, just two items to fix:
> 
> * Please mention the issue number this PR references to in the description something like `This PR fixes #<issue-number>` this will automatically close the issue once the PR is merged.
> * The blank space at the top of the head `Mailing Lists` can be reduced a bit.

Thank you. I have done that

**Comment by Nikhil-Ladha** [comment]
I think by mistake, you have set the issue number as the PR number itself 😅

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
Yea! 🥳

**Pull request merged**
