### PR TITLE
Adding Kush Trivedi as contributor

### PR DESCRIPTION
**Pull request by willcalcote**
Signed-off-by: Will Calcote <wmcalcote@gmail.com>

This PR fixes issue #148.

### CODE REVIEW

**Comment by ashiscs** [comment]
LGTM !!

**Comment by leecalcote** [comment]
Good to go with this picture, @kushthedude?

**Comment by kushthedude** [comment]
> Good to go with this picture, @kushthedude?

Cant be more perfect :smile:

**Comment by leecalcote** [comment]
> > Good to go with this picture, @kushthedude?
> 
> Cant be more perfect 😄

Well said. 😆

**Pull request merged**
