### PR TITLE
corrected the navbar issue

### PR DESCRIPTION
**Pull request by reveurguy**
**Description**
corrected the navbar color issue.
This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Neilblaze** [comment]
@reveurguy good job!

But I would like to point out two things over here.

- The navbar of the [meshery](https://meshery.io/) site doesn't look like what it is in your deploy [preview](https://deploy-preview-327--mesheryio.netlify.app/). Notice that in the [Meshery](https://meshery.io/) landing page & [programs](https://meshery.io/programs/) page, the navbar seems to be blended into the background with a greenish gradient (follow [Layer5 brand](https://layer5.io/brand) guide for more info). What you have done is setting the background color of the navbars to `#3C494F`, which does fix the problem for #326 & #325 , but at the same time reflects change on both the pages. So, try to tackle it differently!

- Fix the DCO. Follow [this](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin) if you get stuck!

**Comment by reveurguy** [comment]
@Neilblaze is there a single header for all pages? or different headers for different pages?

**Comment by Neilblaze** [comment]
In jekyll, to create a full fledged site.page, we break the page into different segments & each of the segments have their own css file. So for different pages there will be different css files or .sass file which post converts to the root css file. A small piece of advice from my side, try to avoid inline css over here!

**Comment by reveurguy** [comment]
@Neilblaze i get this error when i am doing git commit -m -s "" :  pathspec " " did not match any files known to git.

**Pull request closed without merging**
