### PR TITLE
Added: Created By & Used By Sections to Landing Page

### LINKED ISSUE #331: Add Created By and Used By section
**Current State of the Meshery.io site**
There is no section that identifies Layer5 as the creator of Meshery. Nor is there a section that highlights users of Meshery.

**Desired State of the Meshery.io site**
Add a new section that contains two headings:

1. Created By
 - Layer5
2. Used By
 - see the list in the [ADOPTERS.md](https://github.com/layer5io/meshery/blob/master/ADOPTERS.md) file in the meshery repo.

**Design Inspiration**
from https://openebs.io
Screen Shot 2020-09-25 at 11 49 28 AM

from https://www.envoyproxy.io
Screen Shot 2020-09-25 at 11 50 57 AM

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by kishore007k**
Signed-off-by: kishore007k <kishorekumarstar07@gmail.com>

**Description**

This PR fixes #331 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Neilblaze** [comment]
Fix the overflow in mobile view.

**Review by Neilblaze — CHANGES_REQUESTED** [review]
I'll recommend to align the section in vertically stacked mode in mobile view.

**Comment by kishore007k** [comment]
Done✌ @Neilblaze

**Comment by Neilblaze** [comment]
Looks better now. But just a little thing, in mobile view, try to fix the padding between two consecutive svg's.

**Review by Neilblaze — APPROVED** [review]
LGTM :+1:

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Screenshot_20200929-161318__01
The Layer5 logo isn't aligned properly, which is also causing the page to spill on the right side.
For mobile, view instead of stacking the logos vertically in 1 line it would be better to keep 2 logo's in a row, it is unnecessarily stretched out too long.

**Comment by kishore007k** [comment]
Like this?
Capture26

**Comment by Nikhil-Ladha** [comment]
Yes @kishore007k . Just the whitespace above and below the heading `Used By` can be reduced a bit.

**Review by Neilblaze — APPROVED** [review]
Nice work! @kishore007k :tada:

**Comment by Nikhil-Ladha** [comment]
Just one last thing, adding a link to the layer5 image directing to the layer5 site would be a good idea.

**Review by Nikhil-Ladha — APPROVED** [review]
Thank you @kishore007k for baring me😆.
Good work here 👌🏼💯

**Pull request merged**
