### PR TITLE
Moved NGINX SM to beta section

### LINKED ISSUE #398: Promote Meshery Adapter for NGINX SM to beta
**Current State of the Meshery.io site**
The Meshery Adapter for NGINX SM is in beta state. 

**Desired State of the Meshery.io site**
The meshery.io should reflect a "beta" status for this adapter. [These lines](https://github.com/layer5io/meshery.io/blob/f73078ee3d23ab671e46c3e14c56e34d1d7b73e6/index.html#L379-L381) should be moved to the "beta" section of the adapters table.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by bartkalanski**
Signed-off-by: Bart Kalanski <bkalanski@gmail.com>

**Description**

This PR fixes  #398

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Looks great.

**Review by leecalcote — APPROVED** [review]
Thank you, @bartkalanski

**Comment by leecalcote** [comment]
@bartkalanski, good stuff. I wonder if you might implement the same update in the README here - https://github.com/layer5io/meshery

**Comment by bartkalanski** [comment]
@leecalcote no problem!

**Pull request merged**
