### PR TITLE
Fix mailing list link with relative link

### LINKED ISSUE #408: [Menu] Change "Mailing List" link to be local to site
**Current State of the Meshery.io site**
The link in the screenshot points to layer5.io/subscribe

**Desired State of the Meshery.io site**
The link in the screenshot should point to meshery.io/subscribe

Screen Shot 2021-03-20 at 11 26 27 PM

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by igallup**
**Description**

This PR fixes #408

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [X] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Your change looks great, @igallup. One small item is to sign-off on your commit. One-time instructions here - https://github.com/layer5io/meshery.io/pull/412/checks?check_run_id=2180969079

Permanent instructions here - https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Review by leecalcote — APPROVED** [review]
Excellent. 👍

**Comment by leecalcote** [comment]
Yay, @igallup! 🎈

**Comment by igallup** [comment]
Thank you!

**Pull request merged**
