### PR TITLE
Added instructions for scoop

### LINKED ISSUE #400: Instructions for installing via Scoop
**Current State of the Meshery.io site**
`mesheryctl` is available via Scoop as a Windows-based package manager.
The meshery.io site doesn't provide users the option of using Scoop to install Meshery.

Screen Shot 2021-02-19 at 5 39 06 PM

**Desired State of the Meshery.io site**
Scoop should be listed as an option under the Windows section. See this repo as a resource - https://github.com/layer5io/scoop-bucket and the https://docs.meshery.io site.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by metonymic-smokey**
Signed-off-by: metonymic-smokey <ahuja.aditi@gmail.com>

**Description**

This PR fixes #400 

**Notes for Reviewers**
1. Added instructions for installing using Scoop, based on the resources linked in the issue.  
2. Possible changes needed in the `Meshery releases page` and `mesheryctl` links. Should I fix those as part of this PR or open a separate issue for those?

**Screenshot of Changes**
image

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by metonymic-smokey** [comment]
@leecalcote ,
Please review this PR and let me know if there are any changes I should make.  
Also, just take a look at the links in the first part of the `Windows User` section. `Meshery releases page` should be highlighted as a llnk too I think.

Thanks!

**Comment by leecalcote** [comment]
Thanks, @metonymic-smokey. Yes, please do go ahead and include other related fixes in this PR, if you would. A couple items to consider:

1. Let's put the Scoop instructions as the first option. Use of this package manager _should_ be more convenient for the user.
2. Let's remove the hyperlink from "Meshery releases page" and move it to `mesheryctl`.
3. Let's avoid use of the phrase "for the same". It's grammatically incorrect (despite it's wildly, popular use in India).
4. You can use the phrases "Using Scoop" and "Using binary". Under "Using binary", put a subsequent line with "Not a Scoop user? Download the `mesheryctl` binary directly."
5. Under Kubernetes, will you update the "Using Manifests" section to include a subsequent line with "Not a Helm user? Use the Meshery manifests directly."

**Comment by metonymic-smokey** [comment]
@leecalcote ,
Thanks for the feedback!  
These are the screenshots after making the changes:
1.
 image

2. 
image

Let me know if there are any changes to be made!
Thanks!

**Comment by leecalcote** [comment]
Well, that was _fast_. 😄 

Looking over these changes, I'm left with very little room to complain. Not good. Not good at all. I need something to complain about. 

Hmm. My complaint is that there is no room to complain. There. I found something. 😉 

Nice work, @metonymic-smokey. 👍

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
