### PR TITLE
New calendar page

### LINKED ISSUE #342: [Calendar] Create independent page for the new calendar
**Current State of the Meshery.io site**
A new calendar provided in #340 has been incorporated into the community page.

**Desired State of the Meshery.io site**
This new calendar can be placed onto its own, standalone page as well at meshery.io/calendar.
The menu item for the calendar can be updated to point to this new page.

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.

### PR DESCRIPTION
**Pull request by Keenal**
**Description**

I created a new page for meshery.io/calendar which displays the calendar. Please let me know if I need to do anything else. Thank you for letting me work on this!

This PR fixes #342 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Neilblaze — CHANGES_REQUESTED** [review]
Thank you @Keenal for your contribution! :smiley: 
But before the PR gets merged, I shall suggest making the following changes.

- In the mobile view for both the `community` & the new `calendar` pages, the styling of those toggle buttons and the text is not properly optimized. This needs to be fixed. I'm sharing a screenshot for reference.

cal_meshery

- We should add a simple header above the calendar on the new `calendar` page. Like - `Subscribe to the community calender & stay updated`.

Any other design upgradations are always welcome if you want.

Also, adding to the note, @Nikhil-Ladha are we aiming to keep both the Google calendar link in the footer section as well as the fullcalendar in the new page as keeping both will create a sort of ambiguity. Or shall it be better to keep the fullcalendar as it will automatically redirect to Google Calendar? What say?

**Comment by Keenal** [comment]
Should I remove the calendar from Community now that we have a page dedicated to that?

**Comment by Nikhil-Ladha** [comment]
> Should I remove the calendar from Community now that we have a page dedicated to the calendar?

You can remove the calendar from there but we need a callout to the newly created page so that people can visit this page and see the meetings.
 
> Edit: I'm sorry but I don't see the need for having two same calendars at different locations. Wouldn't just one suffice? We can also include the bit[dot]ly link somewhere around the calendar so people can subscribe to it? @leecalcote

We have that link already, if you check out the calendar icon in the footer of the site, you will find that.

**Comment by Nikhil-Ladha** [comment]
Also, I think we need some good modifications in the calendar otherwise (not to be rude) but the calendar doesn't make much sense to me right now. The design, the features available in the calendar, and everything.

**Comment by Nikhil-Ladha** [comment]
Lastly, @Keenal if you can please fix the DCO issue by following the steps listed here:
https://github.com/layer5io/meshery.io/pull/372/checks?check_run_id=1351122930

**Comment by Keenal** [comment]
Thanks for suggesting me with the improvements @Nikhil-Ladha. I took them into consideration and I have come up with slight modifications. Please look at the image below. The titles that are highlighted green are the changes I was thinking of. I think it would be better to move the contributors section under "Connect" because if they are contributing to this project, you would like to connect to them as they have provided their GitHub and Twitter links. And in place of where Contributors section originally was, I want to keep that just for community purposes. So "Join the Community" will have the following:

1. The connect section that has four points to it (join, watch, access, read)
2. a link to the new Calendar Page
3. Stay up to date section

The new calendar page will display the calendar and will have a link (bit[dot]ly) so the people can add meshery to their own calendar.

Sorry if this is not what you wanted. 

meshery_design

**Comment by Nikhil-Ladha** [comment]
For the time being I would suggest not to change the sitemap of the website, which is moving the contributors out of community page and adding a new option under connect.

**Comment by leecalcote** [comment]
@Keenal we love that you're giving deeper thought here. I welcome you to join the Layer5 community here - http://slack.layer5.io. Ping me when you do, let's chat about sitemaps.

**Pull request closed without merging**
