### PR TITLE
Fixed the community meetings calendar

### LINKED ISSUE #356: Fix the Google calendar sync for Fullcalender
**Description**

In the [community](https://meshery.io/community/) page of Meshery site, the Fullcalender is not syncing with the Google calendar API. This needs to be fixed.

**Useful Resources**
- [FullCalender Docs](https://fullcalendar.io/docs/v3/google-calendar)
- [Google API](https://github.com/layer5io/meshery.io/blob/fefecabbe833f0d806d121bd1f6172cc0923d849/community.html#L37) key. 

**Screenshots**

fullcalendar

**Enviroment:**
 - OS: [e.g. Windows, Ubuntu]
 - Browser: [e.g. Chrome, Firefox]
 - Device: [e.g. laptop, Android]

---
[Optional] **To Reproduce**
1. Go to [community](https://meshery.io/community/)
3. Scroll down to the #Connect 
4. See error!

### PR DESCRIPTION
**Pull request by jlcastrogro**
Signed-off-by: José Luis Castro Guerrero <jlcastrogro@gmail.com>

**Description**

The calendar did not show the community meetings

This PR fixes #356

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Neilblaze — APPROVED** [review]
LGTM :+1: 
Thank you @jlcastrogro :tada:

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
@jlcastrogro haha! Awesome.

Will you open a new issue to update the "calendar" menu item to point to a new page that only has the calendar on it? The calendar can still be shown on the community page, too.

**Comment by Nikhil-Ladha** [comment]
Also, I think there are couple of responsive issues with the current calendar. Can you add them too in that issue?

**Comment by jlcastrogro** [comment]
@leecalcote @Nikhil-Ladha will you to open a new issue?

**Comment by leecalcote** [comment]
@jlcastrogro here we are - https://github.com/layer5io/meshery.io/issues/368

**Pull request merged**
