### PR TITLE
 Added the community calendar and fixed issue#322 and the issue with my previous PR

### PR DESCRIPTION
**Pull request by prasanjit15**
Hii, I have fixed issue[#322](https://github.com/layer5io/meshery.io/issues/322) by adding the community calendar and making the necessary changes. Kindly verify and merge it.

### CODE REVIEW

**Comment by Nikhil-Ladha** [comment]
@prasanjit15 good work here. 
If you could just follow [this](https://github.com/layer5io/meshery.io/pull/337/checks?check_run_id=1193971801) to pass the DCO check.

**Comment by prasanjit15** [comment]
@Nikhil-Ladha I guess I have to make a new PR then?

**Comment by Nikhil-Ladha** [comment]
> @Nikhil-Ladha I guess I have to make a new PR then? Sorry, but I have never done such things previously. Can you guide me throughout?

No buddy, follow the link I mentioned above. It lists the steps to take for fixing that.

**Comment by prasanjit15** [comment]
@Nikhil-Ladha All tests have passed you can now merge it. :)

**Review by Nikhil-Ladha — APPROVED** [review]
Thank you @prasanjit15 !

**Comment by prasanjit15** [comment]
> Thank you @prasanjit15 !

Welcome :)

**Comment by prasanjit15** [comment]
@Nikhil-Ladha will you please add the hacktoberfest-accepted label to the PR

**Pull request merged**
