### PR TITLE
[meshery.io] fixed the text overflow issue in the card

### LINKED ISSUE #439: Increase the width of the performance tests run card
**Description**

Text is overflowing on mobile view. 

**Expected Behavior**

Text should remain inside card on mobile view.
Increase the Width of the card to rectify this.

**Screenshots**

Screenshot_2021-05-02 Meshery The Service Mesh Manager

### PR DESCRIPTION
**Pull request by samirparhi-dev**
Signed-off-by: Samir Parhi <samirparhi@gmail.com>

**Description**
fixed the text overflow issue in the card (the performance test run info card)

This PR fixes #439 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

Change screenshot:

evidence

### CODE REVIEW

**Comment by chinmaym07** [comment]
Hey @samirparhi-dev ... 
One more small thing to update here in the home page description .. Change ``` Meaure ``` to ``` Measure ```

image

**Review by leecalcote — APPROVED** [review]
Excellent. Thank you, @samirparhi-dev 👍

**Comment by leecalcote** [comment]
Whoo-hoo, @samirparhi-dev! 🎈

**Comment by samirparhi-dev** [comment]
Thank you @leecalcote. Thanks a lot, @Anita-ihuman for your guidance in completing my first PR.

**Pull request merged**
